# Generated by Django 3.1.6 on 2021-03-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('deptid', models.IntegerField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('emptype', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empapp.departmentmodel')),
            ],
        ),
    ]
